import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/navigation/Nav";
import NavLeftWrapper from "@/components/layout/navigation/NavLeftWrapper";
import { TodoSearchProvider } from "@/context/TodoSearchContext";
import Providers from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <TodoSearchProvider>
            <div className="w-full h-screen">
              <Nav />
              <div className="h-[calc(100%-4.5rem)] flex">
                <NavLeftWrapper />
                <div className="w-full h-full overflow-y-auto">{children}</div>
              </div>
            </div>
          </TodoSearchProvider>
        </Providers>
      </body>
    </html>
  );
}
