import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/navigation/Nav";
import NavLeft from "@/components/layout/navigation/NavLeft";
import { TodoSearchProvider } from "@/context/TodoSearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <TodoSearchProvider>
          <div className=" w-full h-screen ">
            <Nav />
            <div className="h-[calc(100%-4.5rem)] flex  ">
              <NavLeft />
              <div className=" w-full h-full overflow-y-auto overflow-auto">
                {children}
              </div>
            </div>
          </div>
        </TodoSearchProvider>
      </body>
    </html>
  );
}
